/**
 * Contract checks for S3-compatible presigned URLs.
 *
 * This implementation is hand-rolled rather than the AWS SDK, so it has to
 * earn that by matching the real thing exactly. The decisive tests compare it
 * against signatures produced by AWS's own `@aws-sdk/s3-request-presigner`,
 * for the same bucket, key, credentials, region and timestamp.
 *
 * If those pass, the canonical request, the credential scope, the string to
 * sign and all four HMACs are right — there is no way to produce those exact
 * signatures by accident.
 *
 * Everything else here guards what a real survey filename exercises and a
 * tutorial example does not: apostrophes, spaces, percent signs, accented
 * characters and nested paths.
 */

import { presignUrl, signingKey, type S3Config } from "../src/lib/storage/s3";

let failures = 0;

function check(name: string, condition: boolean, detail?: string) {
  if (condition) {
    console.log(`  ok    ${name}`);
  } else {
    failures += 1;
    console.log(`  FAIL  ${name}${detail ? `  →  ${detail}` : ""}`);
  }
}

console.log("\nobject storage contract checks\n");

// ----------------------------------- signatures the AWS SDK itself produced ---
// These are NOT values this implementation generated. They came from AWS's own
// `@aws-sdk/s3-request-presigner` — the library that mints the presigned URLs
// every S3 tutorial uses — run against the same bucket, key, credentials,
// region and timestamp, and copied here.
//
// That external origin is the whole point. Finding them took installing the
// real SDK and diffing, which is how the missing `X-Amz-Content-Sha256` query
// parameter turned up: without it the signature is well-formed, plausible, and
// rejected by every provider. A golden value generated by the code under test
// would never have caught that.
//
// The `x-id` and `x-amz-checksum-mode` parameters are the SDK's own additions.
// They are passed through here only so both sides sign an identical parameter
// set; this implementation has no reason to emit them.

const r2: S3Config = {
  endpoint: "https://abc123.r2.cloudflarestorage.com",
  region: "auto",
  bucket: "tdr-job-files",
  accessKeyId: "TESTKEYID",
  secretAccessKey: "testsecretkey",
};
const AT = new Date("2026-09-14T12:00:00Z");

const sdkVectors: Array<{
  label: string;
  method: "GET" | "PUT";
  key: string;
  extras: Record<string, string>;
  signature: string;
}> = [
  {
    label: "PUT, plain key",
    method: "PUT",
    key: "jobs/abc/survey.dwg",
    extras: { "x-id": "PutObject" },
    signature: "1a7453e84178c21cfdfeea1c82a6b3738e62177dca2145939c41d785f40506cf",
  },
  {
    label: "GET, plain key",
    method: "GET",
    key: "jobs/abc/survey.dwg",
    extras: { "x-amz-checksum-mode": "ENABLED", "x-id": "GetObject" },
    signature: "70e6e1b461affafa4711b3cf648a37f9a6898bac32e81cbf8ea2e59d971715b0",
  },
  {
    label: "PUT, apostrophe, spaces and parentheses",
    method: "PUT",
    key: "jobs/a/O'Brien survey (rev 2).dwg",
    extras: { "x-id": "PutObject" },
    signature: "971ef3e81c1c7b0d5e4ae4f6fae26b21692dca4da767b497c31f2a1d4b524d25",
  },
  {
    label: "PUT, accented characters and a percent sign",
    method: "PUT",
    key: "jobs/a/Topograf\u00eda 100%.las",
    extras: { "x-id": "PutObject" },
    signature: "3ce5f9b06a0e57cbbd9179aaae17b03a26c3c0fe0e5b190e5702f0aedd8142cf",
  },
];

for (const vector of sdkVectors) {
  const url = presignUrl({
    config: r2,
    method: vector.method,
    key: vector.key,
    expiresIn: 3600,
    query: vector.extras,
    now: AT,
  });
  const got = new URL(url).searchParams.get("X-Amz-Signature");
  check(`matches the AWS SDK — ${vector.label}`, got === vector.signature, String(got));
}

// The signing key derivation, exercised through a known-good end-to-end
// signature above, is also checked for shape: four chained HMACs, 32 bytes.
const derived = signingKey("testsecretkey", "20260914", "auto", "s3");
check("the signing key is 32 bytes", derived.length === 32, String(derived.length));
check(
  "a different date derives a different key",
  !signingKey("testsecretkey", "20260915", "auto", "s3").equals(derived),
);
check(
  "a different region derives a different key",
  !signingKey("testsecretkey", "20260914", "us-east-1", "s3").equals(derived),
);

// --------------------------------------------------------------- structure ---
const put = presignUrl({
  config: r2,
  method: "PUT",
  key: "jobs/abc/1234-survey.dwg",
  expiresIn: 3600,
  now: new Date("2026-09-14T12:00:00Z"),
});
const putUrl = new URL(put);

check("the bucket is in the path", putUrl.pathname.startsWith("/tdr-job-files/"), putUrl.pathname);
check("the key follows the bucket", putUrl.pathname.endsWith("/jobs/abc/1234-survey.dwg"));
check("slashes in the key are not escaped", !putUrl.pathname.includes("%2F"), putUrl.pathname);
check("the algorithm is declared", putUrl.searchParams.get("X-Amz-Algorithm") === "AWS4-HMAC-SHA256");
check("expiry is carried", putUrl.searchParams.get("X-Amz-Expires") === "3600");
check("only host is signed", putUrl.searchParams.get("X-Amz-SignedHeaders") === "host");
// The parameter whose absence cost an afternoon. It must be in the query
// string, not only in the canonical request.
check(
  "the unsigned-payload marker is a query parameter",
  putUrl.searchParams.get("X-Amz-Content-Sha256") === "UNSIGNED-PAYLOAD",
  String(putUrl.searchParams.get("X-Amz-Content-Sha256")),
);
check(
  "the credential carries the scope",
  putUrl.searchParams.get("X-Amz-Credential") === "TESTKEYID/20260914/auto/s3/aws4_request",
  String(putUrl.searchParams.get("X-Amz-Credential")),
);
check("a signature is present", /^[0-9a-f]{64}$/.test(putUrl.searchParams.get("X-Amz-Signature") ?? ""));

// The secret must never appear in the URL — the failure would be catastrophic
// and entirely silent, since the URL would still work.
check("the secret key is not in the URL", !put.includes("testsecretkey"));
check("the secret key is not in the URL, encoded", !put.includes(encodeURIComponent("testsecretkey")));

// ----------------------------------------------------------- determinism ----
const again = presignUrl({
  config: r2,
  method: "PUT",
  key: "jobs/abc/1234-survey.dwg",
  expiresIn: 3600,
  now: new Date("2026-09-14T12:00:00Z"),
});
check("the same inputs produce the same URL", put === again);

const later = presignUrl({
  config: r2,
  method: "PUT",
  key: "jobs/abc/1234-survey.dwg",
  expiresIn: 3600,
  now: new Date("2026-09-14T12:00:01Z"),
});
check("a different second produces a different signature", put !== later);

const otherKey = presignUrl({
  config: r2, method: "PUT", key: "jobs/abc/other.dwg",
  expiresIn: 3600, now: new Date("2026-09-14T12:00:00Z"),
});
check("a different key produces a different signature", put !== otherKey);

const asGet = presignUrl({
  config: r2, method: "GET", key: "jobs/abc/1234-survey.dwg",
  expiresIn: 3600, now: new Date("2026-09-14T12:00:00Z"),
});
check("the method is part of the signature", put !== asGet);

// ------------------------------------------------- real filename encoding ---
// AWS's example is "test.txt". Survey deliverables are not.
const awkward: Array<[string, string]> = [
  ["jobs/a/O'Brien survey.pdf", "%27"],
  ["jobs/a/site plan (rev 2).dwg", "%28"],
  ["jobs/a/100% complete.pdf", "%25"],
  ["jobs/a/Topografía.las", "%C3%ADa"],
  ["jobs/a/plus+sign.e57", "%2B"],
  ["jobs/a/star*.rcp", "%2A"],
];

for (const [key, expectedFragment] of awkward) {
  const url = presignUrl({
    config: r2, method: "PUT", key,
    expiresIn: 3600, now: new Date("2026-09-14T12:00:00Z"),
  });
  const path = new URL(url).pathname;
  check(
    `"${key.split("/").pop()}" is encoded (${expectedFragment})`,
    path.includes(expectedFragment),
    path,
  );
  check(
    `"${key.split("/").pop()}" keeps its path separators`,
    (path.match(/\//g) ?? []).length === 4,
    path,
  );
}

// A space must become %20, never "+". S3 treats them differently and the
// signature would not match.
const spaced = presignUrl({
  config: r2, method: "PUT", key: "jobs/a/site plan.pdf",
  expiresIn: 3600, now: new Date("2026-09-14T12:00:00Z"),
});
check("a space encodes as %20, not +", new URL(spaced).pathname.includes("%20"));
check("a space does not encode as +", !new URL(spaced).pathname.includes("+"));

// --------------------------------------------------------- download names ---
const download = presignUrl({
  config: r2,
  method: "GET",
  key: "jobs/abc/survey.pdf",
  expiresIn: 300,
  query: { "response-content-disposition": 'attachment; filename="Final Survey.pdf"' },
  now: new Date("2026-09-14T12:00:00Z"),
});
check(
  "a download filename is carried",
  download.includes("response-content-disposition"),
);
check(
  "extra query parameters change the signature",
  new URL(download).searchParams.get("X-Amz-Signature") !==
    new URL(asGet).searchParams.get("X-Amz-Signature"),
);
// Query parameters must be sorted, or the signature will not verify.
const query = new URL(download).search.replace(/^\?/, "").split("&").map((p) => p.split("=")[0]);
const withoutSignature = query.filter((k) => k !== "X-Amz-Signature");
check(
  "query parameters are sorted",
  JSON.stringify(withoutSignature) === JSON.stringify([...withoutSignature].sort()),
  JSON.stringify(withoutSignature),
);

console.log("");
if (failures > 0) {
  console.log(`${failures} storage check(s) FAILED.\n`);
  process.exit(1);
}
console.log("All object storage checks passed.\n");
