-- ===========================================================================
-- TDR Engineering — proposal upload storage (spec §9, §15)
--
-- Private bucket. Uploads are written server-side with the service role after
-- file-type and file-size validation; staff read them through short-lived
-- signed URLs generated by the admin area. Nothing here is publicly readable.
-- ===========================================================================

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'proposal-uploads',
  'proposal-uploads',
  false,
  26214400, -- 25 MB per file; large CAD/BIM/point-cloud data is explicitly out
            -- of scope for the proposal form (spec §9).
  array[
    'application/pdf',
    'image/jpeg',
    'image/png',
    'image/heic',
    'image/webp',
    'image/tiff',
    'application/msword',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    'application/vnd.ms-excel',
    'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    'application/zip',
    'text/plain'
  ]
)
on conflict (id) do update
  set public = excluded.public,
      file_size_limit = excluded.file_size_limit,
      allowed_mime_types = excluded.allowed_mime_types;

-- Staff may read objects in the bucket. No anon policy at all: the public
-- never reads from this bucket directly.
drop policy if exists "proposal uploads staff read" on storage.objects;
create policy "proposal uploads staff read" on storage.objects
  for select to authenticated
  using (bucket_id = 'proposal-uploads' and is_staff());
